### ISSUE TITLE
Question: Does my library qualify as derivative work?

### ISSUE THREAD

**Issue by rnd0101** [jsongraph/jsongraph.py#5]
Hi!

I got interested in JSON graph format, but "jsongraph.py" was not quite suitable for my needs, so I created my own, limited version:

https://github.com/rnd0101/json-graph-lite

I believe very little is left from the code of this library, but still could be nice if you are still interested, let me know if I stepped on you intellectual property somehow and need to indicate it more prominently. My intention is to publish it as Python package on PyPI.

Thanks!

**Comment by wshayes** [comment]
The licensing was supposed to be completely permissive - so whatever you did with it is fine by me. It sounds like your library doesn't adhere to the JGF JSONSchema. We updated the library to make nodes a dictionary based on several requests. Can I ask why you needed to make the nodes a list?

I also appreciate that you clearly indicate that this does not support JSON Graph Format.

**Comment by rnd0101** [comment]
Thanks! Maybe, I will add a couple of helpers to support dictionary variant later.

The problem with dictionary is that JSON mixes-up integers and strings. And in my case I do not want to restore or loose that information. With list of objects the round-trip is smoother.

My library is not supposed to be optimized as I need to deal with relatively small graphs. If optimizations were required, then classes may have additional hash tables, etc. Having dictionary does not help. One more reason is that handling both nodes and edges in the same way makes the format more uniform.

**Comment by rnd0101** [comment]
I've added (experimental) support for JGF and added examples to tests (JSON-to-JSON roundtrip) directly from [jsongraph/json-graph-specification](https://github.com/jsongraph/json-graph-specification).

However, I have not checked JGF support more than that (not even sure what needs to be done for that).

Plus, of course, my library does not use any optimizations, so maybe not suitable for large graphs.
